<div class="col-md-12 kid-content-holder kid-contact-holder">
    <br/>
    <p style="font-size: 23px;">
        You may contact us at <a href="mailto:office@kidstatistics.com" target="_top">office@kidstatistics.com</a>
    </p>
</div>

<div class="col-md-12 kid-content-holder" style="text-align: center;">
    <br/>
    <p style="font-size: 23px;">
        Phone: <br/>
            +4 0755 110 791 <br/>
            +4 0755 110 792 <br/>
            +4 0755 110 793 <br/>
    </p>
</div>

<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>
<br/><br/><br/><br/><br/><br/><br/><br/><br/><br/><br/>