<div class="col-md-12 kid-about-holder">
    <div class="col-md-12 kid-content-holder">
        <h1>Data validation</h1>
        <ul class="kid-services-ul">
            <li>Logic</li>
            <li>Quality</li>
            <li>Accordance with specifications</li>
        </ul>
    </div>
    <div class="col-md-12 kid-content-holder">
        <h1>Data formatting</h1>
        <ul class="kid-services-ul">
            <li>Cleaning</li>
            <li>Labelling</li>
        </ul>
    </div>
    <div class="col-md-12 kid-content-holder">
        <h1>Additional DP Services</h1>
        <ul class="kid-services-ul">
            <li>Data Weighting</li>
            <li>Quota Selection</li>
            <li>Merging Databases</li>
            <li>Inserting Coding</li>
            <li>Restructuring Databases</li>
            <li>Customised DP tasks according to client specifications</li>
        </ul>
    </div>
    <div class="col-md-12 kid-content-holder">
        <h1>Delivering multiple data formats</h1>
        <ul class="kid-services-ul">
            <li>SPSS</li>
            <li>Excel (codes &amp; labels)</li>
            <li>CSV</li>
            <li>ASCII</li>
            <li>Toplines (frequencies)</li>
            <li>Tables</li>
        </ul>
    </div>
</div>